import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import CardProject from "@/components/CardProject";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Kelvin Nicolau</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main>
        <Header />
        <div className={styles.Home}>
          <div className={styles.imageContainer}>
            <h1>Hello, world!</h1>
          </div>
          <div id="about" className={styles.containerAbout}>
            <div className={styles.retratoContainer}>
              <img src="/images/eu-kelvin.jpeg" alt="Image" />
            </div>
            <div className={styles.textContainer}>
              <h2>I'm Kelvin Nicolau Almeida Miranda</h2>
              <p>
                Bachelor in Computer Science from URI
                Santo Ângelo and currently working at GH Brandtech. During my
                journey, I contributed to significant projects, including the
                development of an Intranet using Concrete CMS and the creation
                of several websites and landing pages, using technologies such
                as HTML, CSS, PHP, Laravel, JavaScript, MySQL, React,
                Typescript, NodeJS, WordPress and Docker.
              </p>
              <p>
                I specialize in Front-End development, focusing on refining
                design and interactivity to provide exceptional experiences for
                users. I have experience in agile methodologies such as Scrum
                and Kanban. I am always looking to learn and grow
                professionally.
              </p>
            </div>
          </div>
          <div id="projects" className={styles.Projects}>
            <h1>Projects</h1>
            <div className={styles.ContainerCards}>
              <CardProject
                imageSrc="/images/rhm-balancas.png"
                projectName="RHM Balanças"
                link="https://rhmbalancas.com/"
              />
              <CardProject
                imageSrc="/images/bamberg.png"
                projectName="Bamberg Alimentos"
                link="https://www.bambergalimentos.com.br/"
              />
              <CardProject
                imageSrc="/images/grupo-front.png"
                projectName="Grupo Front"
                link="https://grupofront.com/"
              />
              <CardProject
                imageSrc="/images/becker.png"
                projectName="Industrial Becker"
                link="https://industrialbecker.com.br/"
              />
               <CardProject
                imageSrc="/images/becker.png"
                projectName="Qintess"
                link="https://qintess.com/"
              />
              <CardProject
                imageSrc="/images/becker.png"
                projectName="Personutri Eduarda"
                link="https://personutrieduardamarques.com.br/"
              />
              <CardProject
                imageSrc="/images/becker.png"
                projectName="NutriHelpIA"
                link="https://nutrihelpia.com/"
              />
            </div>
          </div>
          <div id="contact" className={styles.Contact}>
            <h1>Contato</h1>
          </div>
        </div>
        <Footer />
      </main>
    </>
  );
}
